title: Alberto Padovan # your name (or website title) here
logo: "/images/profile_photo_circle_crop.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral Research Associate at University of Illinois, Urbana-Champaign
  <br><br>
  Fluid Mechanics | Flow Control | Model Reduction | Dynamical Systems Theory
  <br><br>
  <a href="https://scholar.google.com/citations?user=ewFYOZkAAAAJ&hl=en">Google Scholar</a> | 
  <a href="https://www.linkedin.com/in/alberto-padovan-7b0416272/">LinkedIn</a>
  <br><br>
  <a href="/projects">Research</a>
   
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
